steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f',
    'Dockerfile-before-https-first',
    '--build-arg=REACT_APP_API_URL=http://35.193.166.251:80/api/v1',
    '-t',
    'us-central1-docker.pkg.dev/gcp-class-14/zainaazhar-repo/zaina-bank-frontend:${COMMIT_SHA}',
    '.'
  ]

  dir: bank-web-gke
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-central1-docker.pkg.dev/gcp-class-14/zainaazhar-repo/zaina-bank-frontend:${COMMIT_SHA}'
  ]

- name: "gcr.io/cloud-builders/gke-deploy"
  args: ['run', 
    '--filename', 'bank-web-gke/frontend.yaml', 
    '--image', 'us-central1-docker.pkg.dev/gcp-class-14/zainaazhar-repo/zaina-bank-frontend:${COMMIT_SHA}', 
    '--location', 'us-central1-a', 
    '--cluster', 'monitoring-cluster']

images:
- 'us-central1-docker.pkg.dev/gcp-class-14/zainaazhar-repo/zaina-bank-frontend:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY